/* THIS FILE IS AUTOGENERATED BY RUN `yarn cic`, YOU DON'T NEED EDIT IT */
import React from 'react'
import ArrowLeft from '~/icons/arrow-left.svg'
import CheveronDown from '~/icons/cheveron-down.svg'
import Close from '~/icons/close.svg'
import Search from '~/icons/search.svg'
import Sort from '~/icons/sort.svg'
import Tune from '~/icons/tune.svg'

const iconsDict = {
  'arrow-left': ArrowLeft,
  'cheveron-down': CheveronDown,
  close: Close,
  search: Search,
  sort: Sort,
  tune: Tune
}

export type IconName = keyof typeof iconsDict

export const iconNames = Object.keys(iconsDict) as IconName[]

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName
}

export default function Icon({ name, ...props }: IconProps) {
  return React.createElement(iconsDict[name], props)
}
